### ISSUE TITLE
Error when crawling with permissions problems

### ISSUE THREAD

**Issue by mcamp** [ros/rospack#58] opened 2016-01-15 19:01 UTC
As suggested by ahendrix I'm creating this issue from answer.ros.org.
There is a problem with autocompletition on folder without enough permissions.
There is a better explanation of this bug here:
http://answers.ros.org/question/224134/error-when-crawling-with-permissions-problems/

Hope I'm posting this issue in the correct place

**Comment by trainman419** [comment] 2016-01-15 20:36
I'm able to reproduce this by doing:

```
mkdir -p /tmp/test/test
chmod a-r /tmp/test
cd /tmp/test/test
rospack list-names >/dev/null
```

`rospack list-names` is one of the commands that is called from within the roscd tab-completion. I redirect stdout to /dev/null so that the error message (on stderr) is more visible.

**Comment by dirk-thomas** [comment] 2016-01-15 22:01
Thanks for reporting this. Since this is a not very common use case it is not likely that the maintainers will have time to implement this. Please consider contributing a PR to make rospack work in this scenario.

**Comment by kamalpandey1993** [comment] 2018-01-02 13:06
rospack find is giving runtime errors on my beaglebone board. Other rospack commands are running fine like rospack depends.
Here is the screenshot

![untitled](https://user-images.githubusercontent.com/18480929/34484604-b611f686-efeb-11e7-8621-44a05a6b5f4b.jpg)

**Comment by dirk-thomas** [comment] 2018-01-02 18:12
@kamalpandey1993 Your issue seems to be unrelated to this ticket. If you fill a separate ticket please make sure to include enough information, in this case e.g. the content of the file which can't be parsed. Please also don't post screen shots but copy the exact message as text in order to make it searchable.

**Comment by justdoGIT** [comment] 2018-01-03 07:34
@dirk-thomas apologies for the inconvenience. I've raised a new issue #86 . please have a look

**Comment by dirk-thomas** [comment] 2018-01-30 17:39
Addressed by #87.

**Closed as completed by dirk-thomas** 2018-01-30 17:39 UTC
